name: footballdays
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.0
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.0
  dio: ^4.0.4
  json_annotation: ^4.3.0
  freezed: ^1.0.0
  flutter_svg: ^0.23.0+1
  jiffy: ^4.1.0

dev_dependencies:
  json_serializable: ^6.0.1
  retrofit_generator: ^3.0.0+2
  build_runner: ^2.1.5

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

